import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/My-Cs/__docusaurus/debug',
    component: ComponentCreator('/My-Cs/__docusaurus/debug', 'ad8'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/config',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/config', '3e0'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/content',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/content', 'a44'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/globalData',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/globalData', 'e32'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/metadata',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/metadata', 'd35'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/registry',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/registry', 'c79'),
    exact: true
  },
  {
    path: '/My-Cs/__docusaurus/debug/routes',
    component: ComponentCreator('/My-Cs/__docusaurus/debug/routes', '10d'),
    exact: true
  },
  {
    path: '/My-Cs/markdown-page',
    component: ComponentCreator('/My-Cs/markdown-page', '41d'),
    exact: true
  },
  {
    path: '/My-Cs/docs',
    component: ComponentCreator('/My-Cs/docs', 'd7a'),
    routes: [
      {
        path: '/My-Cs/docs/python/Functions-vs-Procedures',
        component: ComponentCreator('/My-Cs/docs/python/Functions-vs-Procedures', 'a58'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/python-conditions',
        component: ComponentCreator('/My-Cs/docs/python/python-conditions', 'bbd'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/python-functions',
        component: ComponentCreator('/My-Cs/docs/python/python-functions', 'aee'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/python-input',
        component: ComponentCreator('/My-Cs/docs/python/python-input', 'f6f'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/python-print',
        component: ComponentCreator('/My-Cs/docs/python/python-print', '7cb'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/python-valid',
        component: ComponentCreator('/My-Cs/docs/python/python-valid', 'd35'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/symbols',
        component: ComponentCreator('/My-Cs/docs/python/symbols', 'c73'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/My-Cs/docs/python/welcome',
        component: ComponentCreator('/My-Cs/docs/python/welcome', 'bf1'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '/My-Cs/',
    component: ComponentCreator('/My-Cs/', 'b68'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
